name: devfest23
description: iOS and Android app for DevFest Lagos 2023, built with Flutter.
publish_to: 'none'

version: 1.0.1+7

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.4.5
  flutter_native_splash: ^2.3.5
  equatable: ^2.0.5
  cloud_firestore: ^4.12.2
  firebase_core: ^2.21.0
  firebase_auth: ^4.12.1
  firebase_messaging: ^14.7.3
  widgetbook: ^3.4.0
  widgetbook_annotation: ^3.1.0
  flutter_svg: ^2.0.9
  font_awesome_flutter: ^10.6.0
  intl: ^0.18.1
  shared_preferences: ^2.2.2
  material_symbols_icons: ^4.2706.0
  iconoir_flutter: ^7.0.0
  regex_router: ^2.0.2
  flutter_screenutil: ^5.9.0
  either_dart: ^1.0.0
  dio: ^5.3.3
  shimmer: ^3.0.0
  cached_network_image: ^3.3.0
  url_launcher: ^6.2.1
  package_info_plus: ^4.2.0
  flutter_local_notifications: ^16.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  widgetbook_generator: ^3.2.0
  build_runner: ^2.4.6


flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - shorebird.yaml
  #   - images/a_dot_ham.jpeg

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Google Sans
      fonts:
        - asset: assets/fonts/GoogleSansDisplay-Bold.ttf
        - asset: assets/fonts/GoogleSansDisplay-Regular.ttf
          style: normal

flutter_native_splash:
  # This package generates native code to customize Flutter's default white native splash screen
  # with background color and splash image.
  # Customize the parameters below, and run the following command in the terminal:
  # dart run flutter_native_splash:create
  # To restore Flutter's default white splash screen, run the following command in the terminal:
  # dart run flutter_native_splash:remove
  background_image: "assets/images/splash-light.png"
  background_image_dark: "assets/images/splash-dark.png"

  # Android 12 handles the splash screen differently than previous versions.  Please visit
  # https://developer.android.com/guide/topics/ui/splash-screen
  # Following are Android 12 specific parameter.
  android_12: